- hosts: application_server
  become: yes
  become_user: ec2-user

  tasks:
    - name: Start docker container
      docker_container:
        name: server
        image: "mckdevopsdemo/server:latest"
        state: started
        recreate: yes
        ports:
        - "3000:3000"