- hosts: jenkins
  become: yes
  become_user: root
  vars:
    jenkins_package_state: latest
    jenkins_plugins:
      - blueocean
    jenkins_plugin_timeout: 120

  pre_tasks:
    - include: helpers/java-8.yml

  tasks:
    - name: Install jenkins
      include_role:
        name: geerlingguy.jenkins

    - name: Add jenkins user to Root group
      usermod:
        name: jenkins
        groups: root
        append: yes

    - name: Restart jenkins
      service:
        name: jenkins
        state: restarted

    - name: Install docker
      yum:
        name: docker
        state: installed

    - name: Start docker daemon
      service:
        name: docker
        state: started

    - name: Install ansible docker agent
      pip:
        name: docker-py
        version: 1.7.0

    - name: Install ansible docker-compose agent
      pip:
        name: docker-compose
        version: 1.7.0

    - name: Docker login
      docker_login:
        username: mckdevopsdemo
        password: Purplec@t1197
        email: vibhav_gulati@mckinsey.com
  roles:
    - geerlingguy.jenkins